version: '2.2'
services:
  

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: elasticsearch-kibana
    environment:
      SERVER_NAME: kibana
      server.port: 5601   
      ELASTICSEARCH_URL: http://elasticsearch-master:9200
    networks:
      - esnet 
    ports:
      - 5601:5601   
  
  


networks:
  esnet:
    external:
      name: shadownet
