version: '2.2'
services:
  
  
  logstash:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-logstash
    container_name: elasticsearch-logstash
    environment:
      jdbc_connection_string: jdbc:mysql://172.19.0.11:3306/mytest?characterEncoding=utf8
      jdbc_user: root
      jdbc_password: root
      elasticsearch_hosts:  elasticsearch-master:9200
      elasticsearch_index:  wcunews-index
      elasticsearch_index_type: wcunews  
      jdbc_condition_sql: select u.id as id,u.university_id as university_id, un.name as colleage,  u.newskey as newskey,u.title as title,u.postdate as postdate,u.link as link,u.tag as tag,u.news_txt as news_txt from wcu_news u inner join university un on un.id=u.university_id where u.id> :sql_last_value
      tracking_column: id
      tracking_column_type: numeric
      use_column_value: "true"
      jdbc_page_size: 10000
      send_schedule_expression: "* * * * *"
      
    networks:
      - esnet 
    command: ["-f", "/usr/share/logstash/config/logstash-jdbc.conf"] 
    


networks:
  esnet:
    external:
      name: shadownet
