version: '2.2'
services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-compose
    container_name: elasticsearch-master
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true 
      - node.name= es6-master
      - node.data=false 
      - node.ingest=true  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch-node1:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-compose
    container_name: elasticsearch-node1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
      - node.master=false 
      - node.data=true 
      - node.name= es6-node1
      - node.ingest=false  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es1:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch-node2:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-compose
    container_name: elasticsearch-node2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
      - node.master=false 
      - node.data=true 
      - node.name= es6-node2
      - node.ingest=false  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: elasticsearch-kibana
    environment:
      SERVER_NAME: kibana
      server.port: 5601   
      ELASTICSEARCH_URL: http://elasticsearch-master:9200
    networks:
      - esnet 
    ports:
      - 5601:5601   
  
  logstash:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-logstash
    container_name: elasticsearch-logstash
    environment:
      jdbc_connection_string: jdbc:mysql://172.19.0.10:3306/mytest
      jdbc_user: root
      jdbc_password: root
      elasticsearch.hosts: elasticsearch-master:9200
      elasticsearch.index: contact-index
      elasticsearch.index.type: contact  
      jdbc.condition.sql: select * from contacts where creation_time >=
    networks:
      - esnet 
      
    
volumes:
  es0:
    driver: local
    driver_opts:
         type: none
         device: /home/ryan/work/es-cluster/es0  
         o: bind
      
  es1:
    driver: local
    driver_opts:
         type: none
         device: /home/ryan/work/es-cluster/es1  
         o: bind
  es2:
    driver: local
    driver_opts:
         type: none
         device: /home/ryan/work/es-cluster/es2  
         o: bind

networks:
  esnet:
    external:
      name: shadownet
