version: '2.2'
services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-compose
    container_name: elasticsearch-master
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true 
      - node.name= es6-master
      - node.data=false 
      - node.ingest=true  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch-node1:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-compose
    container_name: elasticsearch-node1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
      - node.master=false 
      - node.data=true 
      - node.name= es6-node1
      - node.ingest=false  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es1:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch-node2:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-compose
    container_name: elasticsearch-node2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
      - node.master=false 
      - node.data=true 
      - node.name= es6-node2
      - node.ingest=false  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: elasticsearch-kibana
    environment:
      SERVER_NAME: kibana
      server.port: 5601   
      ELASTICSEARCH_URL: http://elasticsearch-master:9200
    networks:
      - esnet 
    ports:
      - 5601:5601   
  
  logstash:
    image: registry.cn-hangzhou.aliyuncs.com/rainbow954/elastic-search-logstash
    container_name: elasticsearch-logstash
    environment:
      jdbc_connection_string: jdbc:mysql://192.168.0.119:3306/gse_db?characterEncoding=utf8
      jdbc_user: root
      jdbc_password: 1234
      elasticsearch_hosts:  elasticsearch-master:9200
      elasticsearch_index:  wcunews-index
      elasticsearch_index_type: wcunews  
      jdbc_condition_sql: SELECT * FROM gse_db.wcu_news
      tracking_column: postdate
      tracking_column_type: numeric
      use_column_value: "false"
      jdbc_page_size: 2000
      
    networks:
      - esnet 
    command: ["-f", "/usr/share/logstash/config/logstash-jdbc.conf"] 
    
volumes:
  es0:
    driver: local
    driver_opts:
         type: none
         device: /home/ryan/work/es-cluster/es0  
         o: bind
      
  es1:
    driver: local
    driver_opts:
         type: none
         device: /home/ryan/work/es-cluster/es1  
         o: bind
  es2:
    driver: local
    driver_opts:
         type: none
         device: /home/ryan/work/es-cluster/es2  
         o: bind

networks:
  esnet:
    external:
      name: shadownet
