version: '3'
services:
  elasticsearch:
    image: youngbe/docker-swarm-elasticsearch:5.5.0
    environment:
      - SERVICE_NAME=elasticsearch
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-AssumeMP"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_cluster
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 1g
          
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    networks:
      - elastic_cluster
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://192.168.100.20:9200

networks:
  elastic_cluster:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.0.10.0/24